### ISSUE TITLE
Unreal Engine v. 4.15 support

### ISSUE THREAD

**Issue by int0h** [ncsoft/Unreal.js#160]
I suppose it's rather a question than an issue... Are you going to provide support for the newer version of the engine and how soon (if you are)? You project looks very promising for me. And in case it's not going to happen soon could you tell me if I can downgrade my Unreal Engine version down to 4.14?

**Comment by nakosung** [comment]
You can find 4.15 support in https://github.com/ncsoft/Unreal.js-core. (I had just no time to submit an update to market place)

**Comment by nakosung** [comment]
I have submitted a build to marketplace just before.

**Comment by schetle** [comment]
I cannot compile on master branch for UE 4.15, nor 4.15.1 due to the conventional changes outlined here: 
https://www.unrealengine.com/blog/unreal-engine-4-15-released

> Every .cpp file includes its matching .h file first - This helps validate that each header is including everything it needs. UnrealBuildTool will check that source files adhere to this convention.

The output is:

`2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\V8\Private\Delegates.cpp(1): error : Expected Delegates.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\V8\Private\DirectoryWatcher.cpp(1): error : Expected DirectoryWatcher.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\V8\Private\JavascriptComponent.cpp(1): error : Expected JavascriptComponent.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\V8\Private\JavascriptContext_Private.cpp(1): error : Expected JavascriptContext_Private.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\V8\Private\JavascriptGlobalDelegates.cpp(1): error : Expected JavascriptGlobalDelegates.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\V8\Private\JavascriptIsolate_Private.cpp(1): error : Expected JavascriptIsolate_Private.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\V8\Private\JavascriptLibrary.cpp(1): error : Expected JavascriptLibrary.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\V8\Private\JavascriptOutputDevice.cpp(1): error : Expected JavascriptOutputDevice.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\V8\Private\JavascriptProcess.cpp(1): error : Expected JavascriptProcess.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\V8\Private\JavascriptProfile.cpp(1): error : Expected JavascriptProfile.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\V8\Private\JavascriptSharedMemoryRegion.cpp(1): error : Expected JavascriptSharedMemoryRegion.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\V8\Private\JavascriptTestLibrary.cpp(1): error : Expected JavascriptTestLibrary.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\V8\Private\Translator.cpp(1): error : Expected Translator.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptUMG\JavascriptComboButton.cpp(1): error : Expected JavascriptComboButton.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptUMG\JavascriptComboButtonContext.cpp(1): error : Expected JavascriptComboButtonContext.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptUMG\JavascriptGameViewport.cpp(1): error : Expected JavascriptGameViewport.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptUMG\JavascriptInGameScene.cpp(1): error : Expected JavascriptInGameScene.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptUMG\JavascriptListView.cpp(1): error : Expected JavascriptListView.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptUMG\JavascriptMenuContext.cpp(1): error : Expected JavascriptMenuContext.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptUMG\JavascriptMenuLibrary.cpp(1): error : Expected JavascriptMenuLibrary.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptUMG\JavascriptMultiBox.cpp(1): error : Expected JavascriptMultiBox.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptUMG\JavascriptMultiLineEditableTextBox.cpp(1): error : Expected JavascriptMultiLineEditableTextBox.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptUMG\JavascriptRichTextBlockHyperlinkDecorator.cpp(1): error : Expected JavascriptRichTextBlockHyperlinkDecorator.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptUMG\JavascriptSearchBox.cpp(1): error : Expected JavascriptSearchBox.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptUMG\JavascriptStyleSetLibrary.cpp(1): error : Expected JavascriptStyleSetLibrary.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptUMG\JavascriptTextBlock.cpp(1): error : Expected JavascriptTextBlock.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptUMG\JavascriptTextModel.cpp(1): error : Expected JavascriptTextModel.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptUMG\JavascriptTileView.cpp(1): error : Expected JavascriptTileView.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptUMG\JavascriptTreeView.cpp(1): error : Expected JavascriptTreeView.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptUMG\JavascriptUICommands.cpp(1): error : Expected JavascriptUICommands.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptUMG\JavascriptUMGBlueprintLibrary.cpp(1): error : Expected JavascriptUMGBlueprintLibrary.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptUMG\JavascriptUMGLibrary.cpp(1): error : Expected JavascriptUMGLibrary.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptUMG\JavascriptWidget.cpp(1): error : Expected JavascriptWidget.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptUMG\JavascriptWindow.cpp(1): error : Expected JavascriptWindow.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptHttp\JavascriptHttpRequest.cpp(1): error : Expected JavascriptHttpRequest.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptWebSocket\JavascriptWebSocket.cpp(1): error : Expected JavascriptWebSocket.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptWebSocket\JavascriptWebSocketServer.cpp(1): error : Expected JavascriptWebSocketServer.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptWebSocket\JSWebSocket.cpp(1): error : Expected JSWebSocket.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptWebSocket\JSWebSocketServer.cpp(1): error : Expected JSWebSocketServer.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptGraphEditor\JavascriptGraphAssetGraphSchema.cpp(1): error : Expected JavascriptGraphAssetGraphSchema.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptGraphEditor\JavascriptGraphConnectionDrawingPolicy.cpp(1): error : Expected JavascriptGraphConnectionDrawingPolicy.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptGraphEditor\JavascriptGraphEdGraph.cpp(1): error : Expected JavascriptGraphEdGraph.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptGraphEditor\JavascriptGraphEditorLibrary.cpp(1): error : Expected JavascriptGraphEditorLibrary.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptGraphEditor\JavascriptGraphEditorWidget.cpp(1): error : Expected JavascriptGraphEditorWidget.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptGraphEditor\JavascriptGraphEdNode.cpp(1): error : Expected JavascriptGraphEdNode.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptGraphEditor\SJavascriptGraphEdNode.cpp(1): error : Expected SJavascriptGraphEdNode.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptGraphEditor\SJavascriptGraphEdNodePin.cpp(1): error : Expected SJavascriptGraphEdNodePin.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptEditor\JavascriptAssetEditorToolkit.cpp(1): error : Expected JavascriptAssetEditorToolkit.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptEditor\JavascriptAssetTypeActions.cpp(1): error : Expected JavascriptAssetTypeActions.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptEditor\JavascriptCommandlet.cpp(1): error : Expected JavascriptCommandlet.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptEditor\JavascriptEditorEngineLibrary.cpp(1): error : Expected JavascriptEditorEngineLibrary.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptEditor\JavascriptEditorGlobalDelegates.cpp(1): error : Expected JavascriptEditorGlobalDelegates.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptEditor\JavascriptEditorInputProcessor.cpp(1): error : Expected JavascriptEditorInputProcessor.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptEditor\JavascriptEditorLibrary.cpp(1): error : Expected JavascriptEditorLibrary.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptEditor\JavascriptEditorPopupWindow.cpp(1): error : Expected JavascriptEditorPopupWindow.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptEditor\JavascriptEditorTab.cpp(1): error : Expected JavascriptEditorTab.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptEditor\JavascriptEditorTabManager.cpp(1): error : Expected JavascriptEditorTabManager.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptEditor\JavascriptEditorTick.cpp(1): error : Expected JavascriptEditorTick.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptEditor\JavascriptEditorToolbar.cpp(1): error : Expected JavascriptEditorToolbar.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptEditor\JavascriptEditorViewport.cpp(1): error : Expected JavascriptEditorViewport.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptEditor\JavascriptEdMode.cpp(1): error : Expected JavascriptEdMode.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptEditor\JavascriptEdModeLibrary.cpp(1): error : Expected JavascriptEdModeLibrary.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptEditor\JavascriptInputEventStateLibrary.cpp(1): error : Expected JavascriptInputEventStateLibrary.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptEditor\JavascriptNotification.cpp(1): error : Expected JavascriptNotification.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptEditor\JavascriptPropertyCustomization.cpp(1): error : Expected JavascriptPropertyCustomization.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptEditor\JavascriptPropertyCustomizationLibrary.cpp(1): error : Expected JavascriptPropertyCustomizationLibrary.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptEditor\JavascriptRawMeshLibrary.cpp(1): error : Expected JavascriptRawMeshLibrary.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptEditor\JavascriptScrubControlPanel.cpp(1): error : Expected JavascriptScrubControlPanel.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptEditor\JavascriptUIExtender.cpp(1): error : Expected JavascriptUIExtender.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptEditor\PropertyEditor.cpp(1): error : Expected PropertyEditor.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptConsole\Private\JavascriptConsoleModule.cpp(1): error : Expected JavascriptConsoleModule.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptConsole\Private\SJavascriptConsole.cpp(1): error : Expected SJavascriptConsole.h to be first header included.
2>F:\Projects\UnrealEngine\Engine\Plugins\UnrealJS\Source\JavascriptConsole\Private\SJavascriptLog.cpp(1): error : Expected SJavascriptLog.h to be first header included.
2>Build canceled.`

**Comment by nakosung** [comment]
@schetle You could build unreal.js as a game-plugin not to get those errors. Anyway, I'll investigate this issue. :)

**Comment by nakosung** [comment]
@schetle It is fixed by https://github.com/ncsoft/Unreal.js-core/commit/b8671c76a984d21eecaa66060d4fa9e152570868

**Comment by schetle** [comment]
@nakosung Great!

I verified that it's compiling and working on my end.
