### ISSUE TITLE
doesn't compile in UE 4.24.3 on Linux

### ISSUE THREAD

**Issue by jonbitzen** [ncsoft/Unreal.js#270]
Followed the instructions, and had the following compilation error:

> [1/8] Compile Module.V8.cpp
In file included from /home/jrailsback/Documents/Unreal/unreal-projects/MyProject/Plugins/UnrealJS/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/V8/Module.V8.cpp:8:
/home/jrailsback/Documents/Unreal/unreal-projects/MyProject/Plugins/UnrealJS/Source/V8/Private/JavascriptContext_Private.cpp:1154:6: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
                                        ProxyFuncMap->Set(context, I.Keyword("ctor"), Function0);
                                        ^~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jrailsback/Documents/Unreal/unreal-projects/MyProject/Plugins/UnrealJS/Source/V8/Private/JavascriptContext_Private.cpp:1155:6: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
                                        ProxyFuncMap->Set(context, I.Keyword("prector"), Function1);
                                        ^~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jrailsback/Documents/Unreal/unreal-projects/MyProject/Plugins/UnrealJS/Source/V8/Private/JavascriptContext_Private.cpp:1161:4: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
                        aftr_v8_template->ToObject(context).ToLocalChecked()->Set(context, I.Keyword("proxy"), ProxyFunctions);
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jrailsback/Documents/Unreal/unreal-projects/MyProject/Plugins/UnrealJS/Source/V8/Private/JavascriptContext_Private.cpp:1306:4: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
                        aftr_v8_template->ToObject(context).ToLocalChecked()->Set(context, I.Keyword("proxy"), ProxyFunctions);
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/jrailsback/Documents/Unreal/unreal-projects/MyProject/Plugins/UnrealJS/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/V8/Module.V8.cpp:12:
/home/jrailsback/Documents/Unreal/unreal-projects/MyProject/Plugins/UnrealJS/Source/V8/Private/JavascriptIsolate_Private.cpp:1189:6: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
                                        function->Call(isolate->GetCurrentContext(), info.This(), 0, nullptr);
                                        ^~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jrailsback/Documents/Unreal/unreal-projects/MyProject/Plugins/UnrealJS/Source/V8/Private/JavascriptIsolate_Private.cpp:1206:6: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
                                        function->Call(isolate->GetCurrentContext(), info.This(), 0, nullptr);
                                        ^~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
6 errors generated.

I fixed those errors by adding "(void)" in front of the lines identified.

Then I got the following linker error:

> Performing 8 actions (16 in parallel)
[1/8] Compile Module.V8.cpp
[2/8] Link (ld) libUE4Editor-V8.so
/home/jrailsback/Documents/Unreal/UnrealEngine/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v15_clang-8.0.1-centos7/x86_64-unknown-linux-gnu/bin/x86_64-unknown-linux-gnu-ld: /home/jrailsback/Documents/Unreal/unreal-projects/MyProject/Plugins/UnrealJS/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/V8/Module.V8.cpp.o: in function `FFrame::FFrame(UObject*, UFunction*, void*, FFrame*, UField*)':
/home/jrailsback/Documents/Unreal/UnrealEngine/Engine/Source/Runtime/CoreUObject/Public/UObject/Stack.h:217: undefined reference to `vtable for FFrame'
/home/jrailsback/Documents/Unreal/UnrealEngine/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v15_clang-8.0.1-centos7/x86_64-unknown-linux-gnu/bin/x86_64-unknown-linux-gnu-ld: /home/jrailsback/Documents/Unreal/unreal-projects/MyProject/Plugins/UnrealJS/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/V8/Module.V8.cpp.o: in function `~FFrame':
/home/jrailsback/Documents/Unreal/UnrealEngine/Engine/Source/Runtime/CoreUObject/Public/UObject/Stack.h:117: undefined reference to `vtable for FFrame'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

Any help to get past the linker error would be very much appreciated!

**Comment by thejustinwalsh** [comment]
https://github.com/ncsoft/Unreal.js-core/issues/53#issuecomment-596613570
